### ISSUE TITLE
Change birthday inputs to datepicker

### ISSUE THREAD

**Issue by barmidrol** [R1cro/SocialNetwork#7]
![screenshot at oct 10 11-53-03](https://cloud.githubusercontent.com/assets/11842839/19230994/3ef72fa2-8ee0-11e6-80f5-00de1b1c89be.png)

**Comment by R1cro** [comment]
https://github.com/R1cro/SocialNetwork/pull/9

**Comment by barmidrol** [comment]
pr #9
